
# +----------------------------------------------------------------------------------------------+ #
# |                                                                                              | #
# |                                      MONGODB DATABASE SETTINGS                               | #
# |                                                                                              | #
# |                          Controls how to connect to the server database.                     | #
# |                                                                                              | #
# +----------------------------------------------------------------------------------------------+ #
database:
  user: ''#'root'
  name: 'lumae' # NEEDS DB NAME
  password: ''#'asdfasdf1'
  host: ''#'cluster0.btzdz.mongodb.net'
  port: ''#'#27017'
  connectionString: 'mongodb+srv://root:asdfasdf1@cluster0.btzdz.mongodb.net/lumae?retryWrites=true&w=majority'
  # +----------------------------------------------------------------------------------------------+ #
  # |                                                                                              | #
  # |                                      DATABASE DEFAULTS                                       | #
  # |                                                                                              | #
  # |                   Default data to store upon connection to MongoDB                           | #
  # |                                                                                              | #
  # +----------------------------------------------------------------------------------------------+ #
defaults:
  chatFormats: #NAME/ID WILL BE DEFAULT
    permission: 'chat.default'
    messageFormat: '%luckperms_prefix% %player_displayname% &8»&7 %player_message%'
    priority: 99999
  joinLeaveFormats: #NAME/ID WILL BE DEFAULT
    permission: 'joinleave.default'
    joinFormat: '&e%player_name% &7has arrived!'
    leaveFormat: '&e%player_name% &7has departed!'
  pluginMessages:
    motd:
      format: '&eWelcome back to Server &7%player_name%!'